jaffle_shop:          # debe coincidir con name: en dbt_project.yml
  target: dev
  outputs:
    dev:
      type: duckdb
      path: bbdd/jaffle_shop.duckdb   # ruta vista desde jaffle_shop/
      schema: main
      threads: 4
